"""Added VerificationToken

Revision ID: 1a06c525945a
Revises: 22aa8a9baaf7
Create Date: 2025-03-27 00:26:01.583974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a06c525945a'
down_revision: Union[str, None] = '22aa8a9baaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_urls_id', table_name='urls')
    op.drop_index('ix_urls_short_url', table_name='urls')
    op.drop_table('urls')
    op.add_column('short_urls', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_urls', 'expires_at')
    op.create_table('urls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('short_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='urls_pkey')
    )
    op.create_index('ix_urls_short_url', 'urls', ['short_url'], unique=True)
    op.create_index('ix_urls_id', 'urls', ['id'], unique=False)
    # ### end Alembic commands ###
